declare module 'focus-visible/dist/focus-visible'
declare module '@mapbox/rehype-prism'
declare module 'next-mdx-remote/hydrate'
declare module 'next-mdx-remote/render-to-string'
declare module 'remark-code-titles'
declare module 'remark-unwrap-images'
declare module 'remark-slug'
declare module 'remark-autolink-headings'
